### ISSUE TITLE
[Feat] 스캐폴딩

### ISSUE THREAD

**Issue by kongnayeon** [dnd-side-project/dnd-10th-2-frontend#1]
### 정보

- 담당자 : @kongnayeon 
- 개요 : 초기세팅
- 기한 :

### 설명

- 프로젝트 스캐폴딩

### 체크리스트

- [x] vite + react 프로젝트 생성
- [x] yarn berry + pnp
- [x] eslint, prettier
- [x] alias 설정
- [x] emotion
- [x] tanstack query
- [x] recoil
- [x] axios
- [x] msw

**Comment by pxxnxx** [comment]
중복된 변수.
